name: car_auction
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_strategy: ^0.3.0
  go_router: ^16.2.4
  flutter_bloc: ^9.1.1
  freezed: ^3.2.3
  dart_mappable: ^4.6.1
  shadcn_ui: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  custom_lint: ^0.7.6
  leancode_lint: ^17.0.0
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  dart_mappable_builder: ^4.6.0


flutter:

  uses-material-design: true
